fix below link error when building debug version.
../../../../lib/libzookeeper.so: undefined reference to `hashtable_iterator_key'
../../../../lib/libzookeeper.so: undefined reference to `hashtable_iterator_value'
collect2: ld returned 1 exit status
make[2]: *** [../testbin/t_zk_client] Error 1

The error is caused by declaring C function as "extern inline",
as no definition would be generated for such function,
when they are not inlined, such as in debug mode with flag "-fno-inline",
the link error would happen.

The error could be avoided by declaring with "static inline" instead,
it generates funciton definition for each translation unit.

Please note that the "inline" keyword in GNU C is not the same with in C++,
You could find the details in http://www.greenend.org.uk/rjk/2003/03/inline.html